In [4]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [16]:
import tensorflow as tf

# Create a variable with initial value 1
zero = tf.Variable(1)

# Create a constant with value 4
one = tf.constant(4)

# Add them
new_value = tf.add(zero, one)
print("new_value:", new_value.numpy())  # .numpy() to get the value

# Update the variable with the new value
zero.assign(new_value)
print("updated zero:", zero.numpy())


new_value: 5
updated zero: 5


In [20]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)

result = tf.add(a, b)
print("Result of addition:", result.numpy())

Result of addition: 5


In [23]:
import tensorflow as tf

# Constant tensor
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
print("Constant:\n", a)

print()

# Variable tensor
b = tf.Variable([[5, 6], [7, 8]], dtype=tf.float32)
print("Variable:\n", b)

print()

# Shape and type
print("Shape of a:", a.shape)
print("Data type of a:", a.dtype)


Constant:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Variable:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[5., 6.],
       [7., 8.]], dtype=float32)>

Shape of a: (2, 2)
Data type of a: <dtype: 'float32'>


In [25]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

# Element-wise addition
z = tf.add(x, y)
print("Addition:", z.numpy())

print()

# Element-wise multiplication
m = tf.multiply(x, y)
print("Multiplication:", m.numpy())

print()

# Broadcasting
a = tf.constant([[1], [2], [3]])  # Shape: (3,1)
b = tf.constant([4, 5])           # Shape: (2,)
print("Broadcast result:\n", tf.add(a, b))  # Shape becomes (3,2)


Addition: [5 7 9]

Multiplication: [ 4 10 18]

Broadcast result:
 tf.Tensor(
[[5 6]
 [6 7]
 [7 8]], shape=(3, 2), dtype=int32)


In [26]:
# Simple immediate operation
x = tf.constant([1.0, 2.0])
y = tf.constant([3.0, 4.0])
z = x + y  # Runs immediately
print("Eager result:", z.numpy())


Eager result: [4. 6.]


In [27]:
@tf.function
def compute(x, y):
    return tf.multiply(x, y) + tf.add(x, y)

x = tf.constant([2.0, 3.0])
y = tf.constant([4.0, 5.0])
print("Graph execution result:", compute(x, y))

# Graph execution is optimized, runs faster, and is useful for production.
# You convert Python code to a TensorFlow graph using @tf.function.

# Behind the scenes, TensorFlow builds a computation graph for compute() for better performance.

Graph execution result: tf.Tensor([14. 23.], shape=(2,), dtype=float32)


In [28]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x ** 2 + 2 * x + 1  # y = x^2 + 2x + 1

# Compute dy/dx
dy_dx = tape.gradient(y, x)
print("Gradient (dy/dx):", dy_dx.numpy())  # Should be 2x + 2 = 8 when x=3

Gradient (dy/dx): 8.0
