In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [4]:
import tensorflow as tf

a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([6, 7, 8, 9, 10])

c = tf.add(a, b)
d = tf.multiply(a, b)

print(c)
print(d)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)


In [ ]:
import tensorflow as tf

random_normal = tf.random.normal([2, 3], mean=0.0, stddev=1.0)
print(random_normal)

print()

random_uniform = tf.random.uniform([2, 3], minval=0, maxval=1)
print(random_uniform)

tf.Tensor(
[[-0.26104233  0.7397498   1.2324532 ]
 [ 1.3516948   1.794302   -0.8276496 ]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[0.4292227  0.39740944 0.6240401 ]
 [0.05455685 0.09075594 0.0459131 ]], shape=(2, 3), dtype=float32)


In [12]:
import tensorflow as tf

# Original tensor
original_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print(original_tensor)

print()

# Reshape the tensor to a different shape
reshaped_tensor = tf.reshape(original_tensor, [3, 2])
print(reshaped_tensor)

print()

# slice the tensor
sliced_tensor = tf.slice(original_tensor, [0, 1], [2, 2])
print(sliced_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
