In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [4]:
import tensorflow as tf

a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([6, 7, 8, 9, 10])

c = tf.add(a, b)
d = tf.multiply(a, b)

print(c)
print(d)

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)


In [5]:
import tensorflow as tf

random_normal = tf.random.normal([2, 3], mean=0.0, stddev=1.0)
print(random_normal)

random_uniform = tf.random.uniform([2, 3], minval=0, maxval=1)
print(random_uniform)

tf.Tensor(
[[ 1.1915033   1.0459775  -1.6179084 ]
 [-0.63551646 -1.5098503   0.02186147]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.89497983 0.4174677  0.8754375 ]
 [0.35161197 0.43895936 0.3010589 ]], shape=(2, 3), dtype=float32)
